export const PROJECTION_GRAPH_FACTORY=Symbol(
    'PROJECTION_GRAPH_FACTORY'
)
export const PROJECTION_CANDIDATE_NODE_FACTORY=Symbol(
    'PROJECTION_CANDIDATE_NODE_FACTORY'
)
export const PROJECTION_CANDIDATE_NODE_DESCRIPTOR_FACTORY=Symbol(
    'PROJECTION_CANDIDATE_NODE_DESCRIPTOR_FACTORY'
)

export const  PROJECTION_NODE_DESCRIPTOR_FACTORY=Symbol(
    ' PROJECTION_NODE_DESCRIPTOR_FACTORY'
)

export const PROJECTION_NODE_FACTORY=Symbol(
    'PROJECTION_NODE_FACTORY'
)

export const FLOW_VIEW_DESCRIPTOR_FACTORY=Symbol(
    'FLOW_VIEW_DESCRIPTOR_FACTORY'
)

export const FLOW_VIEW_FACTORY=Symbol(
    'FLOW_VIEW_FACTORY'
)