export type ExecutionStage =
  | 'EVENT_RECEIVED'
  | 'FRAME_CREATED'
  | 'PLUGIN_STARTED'
  | 'PLUGIN_COMPLETED'
  | 'DECISION_RECEIVED'
  | 'STATE_UPDATED'
  | 'TRANSITION_STARTED'
  | 'TRANSITION_COMPLETED'
  | 'EXECUTION_COMPLETED'
  | 'EXECUTION_FAILED';