export const FLOW_SESSION_DESCRIPTOR_FACTORY=Symbol(
    'FLOW_SESSION_DESCRIPTOR_FACTORY'
)
export const FLOW_SESSION_FACTORY=Symbol(
    'FLOW_SESSION_FACTORY'
)
export const COMPOSITION_SESSION_FACTORY=Symbol(
    'COMPOSITION_SESSION_FACTORY'
)