export const PROJECTION_SEED_EXECUTOR=Symbol(
    'PROJECTION_SEED_EXECUTOR'
)
export const PROJECTION_GRAPH_EXECUTOR=Symbol(
    "PROJECTION_GRAPH_EXECUTOR"
)
export const PROJECTION_CANDIDATE_NODE_EXECUTOR=Symbol(
    'PROJECTION_CANDIDATE_NODE_EXECUTOR'
)
export const PROJECTION_NODE_EXECUTOR=Symbol(
    'PROJECTION_NODE_EXECUTOR'
)
export const FLOW_VIEW_EXECUTOR=Symbol(
    'FLOW_VIEW_EXECUTOR'
)