export const RUNTIME_SNAPSHOT =
Symbol(
'RUNTIME_SNAPSHOT'
);
export const RUNTIME_READER =
Symbol(
'RUNTIME_READER'
);

export const RUNTIME_WRITER =
Symbol(
'RUNTIME_WRITER'
);
export const RUNTIME_STORE =
Symbol(
'RUNTIME_STORE'
);

export const RUNTIME_TRACKER =
Symbol(
'RUNTIME_TRACKER'
);

export const RUNTIME_JOURNAL =
Symbol(
'RUNTIME_JOURNAL'
);

export const RUNTIME_PATCH_BUILDER =
Symbol(
'RUNTIME_PATCH_BUILDER'
);

export const RUNTIME_COORDINATOR =
Symbol(
'RUNTIME_COORDINATOR'
);

export const RUNTIME_SNAPSHOT_READER =
Symbol(
'RUNTIME_SNAPSHOT_READER'
);

export const
RUNTIME_RECOVERY_COORDINATOR =
Symbol(
'RUNTIME_RECOVERY_COORDINATOR'
);

export const
RUNTIME_JOURNAL_READER =
Symbol(
'RUNTIME_JOURNAL_READER'
);
export const
FLOW_IDENTITY =
Symbol(
'FLOW_IDENTITY'
);
export const RUNTIME_VIEW_PROVIDER =
  Symbol('RUNTIME_VIEW_PROVIDER');

  export const
RUNTIME_CHANGE_DETECTOR =
Symbol(
'RUNTIME_CHANGE_DETECTOR'
);