export enum PaymentStatus {
    PENDING = 'PENDING',
    PROCESSING = 'PROCESSING',
    REQUIRES_ACTION = 'REQUIRES_ACTION',
    AUTHORIZED = 'AUTHORIZED',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED',
    CANCELED = 'CANCELED',
    REFUNDED = 'REFUNDED'


}
