export const DECISION_PATCH_MIDDLEWARE =
Symbol('DECISION_PATCH_MIDDLEWARE');
export const RUNTIME_MIDDLEWARE=Symbol(
    "RUNTIME_MIDDLEWARE"
)
export const TRANSITION_MIDDLEWARE=Symbol(
    "TRANSITION_PIPELINE"
)