export const DECISION_PATCH_MIDDLEWARE =
Symbol('DECISION_PATCH_MIDDLEWARE');
export const RUNTIME_MIDDLEWARE=Symbol(
    "RUNTIME_MIDDLEWARE"
)
export const TRANSITION_MIDDLEWARE=Symbol(
    "TRANSITION_PIPELINE"
)
export const  RUNTIME_DIFF_MIDDLEWARE=Symbol(
    "RUNTIME_DIFF_MIDDLEWARE"
)
export const EXECUTION_COMMIT_MIDDLEWARE=Symbol(
    'EXECUTION_COMMIT_MIDDLEWARE'
)