export const EXECUTION_SESSION_FACTORY =
  Symbol('EXECUTION_SESSION_FACTORY');

export const EXECUTION_METADATA_FACTORY=Symbol(
    'EXECUTION_METADATA_FACTORY'
)

export const EXECUTION_STATE_FACTORY=Symbol(
    'EXECUTION_STATE_FACTORY'
)
export const EXECUTION_RUNTIME_FACTORY=Symbol(
    'EXECUTION_RUNTIME_FACTORY'
)